name: "test_everything"
on: [push, workflow_dispatch]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
    
      - name: Setup Node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '20'
    
      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        run: yarn test
    
      - name: Build and deploy
        run: |
          yarn build
          yarn test:e2e

      - name: JUnit reports
        uses: xportation/junit-coverage-report@v1.0.3
        with:
          junit-path: reports/*.xml
